# CircleCI configuration for Spectrum

# Aliases
aliases:

  # Cache Management
  - &restore-yarn-cache
    keys:
      - v1-yarn-{{ arch }}-{{ checksum "package.json" }}
      - v1-yarn-{{ arch }}-

  - &save-yarn-cache
    paths:
      - node_modules
      - mobile/node_modules
      - ~/.cache/yarn
    key: v1-yarn-{{ arch }}-{{ checksum "package.json" }}

  - &yarn
    |
      yarn
      cd ./mobile && yarn && yarn setup

  - &install-rethinkdb
    name: Install RethinkDB 2.3.5
    command:
      |
        echo "deb http://download.rethinkdb.com/apt jessie main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
        wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install rethinkdb=2.3.5~0jessie

  - &start-rethinkdb
    name: Start RethinkDB
    command: rethinkdb --bind all
    background: true

  - &setup-and-build-web
    name: Setup and build
    command:
      |
        node -e "const setup = require('./shared/testing/setup.js')().then(() => process.exit())"
        yarn run build:web
        yarn run build:api

  - &start-api
    name: Start the API in the background
    command: TEST_DB=true yarn run dev:api
    background: true

  - &start-web
    name: Start web client in the background
    command: yarn run dev:web
    background: true

defaults: &defaults
  working_directory: ~/spectrum

js_defaults: &js_defaults
  <<: *defaults
  docker:
    - image: circleci/node:8

macos_defaults: &macos_defaults
  <<: *defaults
  macos:
    xcode: "9.2.0"

version: 2
jobs:

  # Set up environment and install required dependencies
  checkout_environment:
    <<: *js_defaults
    steps:
      - checkout

      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache

      - persist_to_workspace:
          root: .
          paths: .

  build_web:
    <<: *js_defaults
    steps:
      - run: *setup-and-build-web

  test_web_unit:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: ~/spectrum
      - run:
          name: Run Unit Tests
          command: yarn run test:ci
      - run:
          name: Danger
          when: always
          command: yarn run danger ci

  # Start db and servers, then run e2e and unit tests
  test_web_e2e:
    <<: *defaults
    docker:
      - image: circleci/node:8-browsers
      - image: redis:3.2.7
      - image: cypress/base:6
    environment:
      TERM: xterm
    steps:
      - attach_workspace:
          at: ~/spectrum
      - run: *install-rethinkdb
      - run: *start-rethinkdb
      - run: sleep 10
      - run: *start-api
      - run: *start-web
      - run: sleep 60
      - run:
          name: Run E2E Tests
          command: yarn run test:e2e

  # Run eslint, flow etc.
  test_static_js:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: ~/spectrum
      - run:
          name: Run Flow
          command: yarn run flow
      - run:
          name: Run ESLint
          command: yarn run lint

  # Tests js of the mobile app
  test_mobile_js:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: ~/spectrum
      - run: cd ./mobile && yarn test:unit

  # Tests native code of the mobile app
  test_mobile_native:
    <<: *macos_defaults
    steps:
      - attach_workspace:
          at: ~/spectrum
      - run:
          name: Install Expo CLI
          command: npm install -g exp
      - run:
          name: Install Detox dependencies
          command: |
            brew tap wix/brew
            brew install applesimutils --HEAD
            npm install -g detox-cli
      - run:
          name: Rebuild Detox frameworks
          command: |
            cd ./mobile
            detox clean-framework-cache
            detox build-framework-cache
      - run:
          name: Start Packager in the background
          command: cd ./mobile && exp start
          background: true
      - run: cd ./mobile && yarn test:e2e

workflows:
  version: 2

  test:
    jobs:
      - checkout_environment
      - build_web:
          requires:
            - checkout_environment
      - test_mobile_js:
          requires:
            - checkout_environment
      - test_web_unit:
          requires:
            - checkout_environment

      # Disabled as Expo is fixing their critical issue with Detox
      # - test_mobile_native:
      #     requires:
      #       - checkout_environment
      - test_web_e2e:
          requires:
            - checkout_environment
            - build_web
      - test_static_js:
          requires:
            - checkout_environment
