# CircleCI configuration for Spectrum

# Aliases
aliases:

  # Cache Management
  - &restore-yarn-cache
    keys:
      - v1-yarn-{{ arch }}-{{ checksum "package.json" }}
      - v1-yarn-{{ arch }}-

  - &save-yarn-cache
    paths:
      - node_modules
      - mobile/node_modules
      - ~/.cache/yarn
    key: v1-yarn-{{ arch }}-{{ checksum "package.json" }}

  - &yarn
    |
      yarn
      cd ./mobile && yarn && yarn setup

  - &install-rethinkdb
    name: Install RethinkDB 2.3.5
    command:
      |
        echo "deb http://download.rethinkdb.com/apt jessie main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
        wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install rethinkdb=2.3.5~0jessie

  - &start-rethinkdb
    name: Start RethinkDB
    command: rethinkdb --bind all
    background: true

  - &setup-and-build-web
    name: Setup and build web
    command:
      |
        cp now-secrets.example.json now-secrets.json
        yarn run build:web

  - &build-api
    name: Build API
    command: yarn run build:api

  - &start-api
    name: Start the API in the background
    command: yarn run start:api:test
    background: true

  - &start-web
    name: Start web client in the background
    command: yarn run dev:web
    background: true

defaults: &defaults
  working_directory: ~/spectrum

js_defaults: &js_defaults
  <<: *defaults
  docker:
    - image: circleci/node:8

macos_defaults: &macos_defaults
  <<: *defaults
  macos:
    xcode: "9.2.0"

version: 2
jobs:

  # Set up environment and install required dependencies
  checkout_environment:
    <<: *js_defaults
    steps:
      - checkout

      - restore-cache: *restore-yarn-cache
      - run: *yarn
      - save-cache: *save-yarn-cache

      - persist_to_workspace:
          root: .
          paths: .

  # Start db and servers, then run e2e and unit tests
  test_web:
    <<: *defaults
    docker:
      - image: circleci/node:8-browsers
      - image: redis:3.2.7
      - image: cypress/base:6
      - image: rethinkdb:2.3.5
    environment:
      TERM: xterm
    steps:
      - attach_workspace:
          at: ~/spectrum
      - run: node -e "const setup = require('./shared/testing/setup.js')().then(() => process.exit())"
      - run: *setup-and-build-web
      - run: *build-api
      - run: *start-api
      - run: *start-web
      # Wait for the API and webserver to start
      - run: ./node_modules/.bin/wait-on http://localhost:3000 http://localhost:3001
      - run:
          name: Run Unit Tests
          command: yarn run test:ci
      - run:
          name: Run E2E Tests
          command: test $CYPRESS_RECORD_KEY && yarn run test:e2e -- --record || yarn run test:e2e

  deploy_alpha:
    <<: *js_defaults
    docker:
      - image: circleci/node:8-browsers
    steps:
      - attach_workspace:
          at: ~/spectrum
      - run:
          name: Install now
          command: sudo npm install --global --unsafe-perm now
      - run: *build-api
      - run:
          name: Deploy and alias API
          command: |
            cd build-api
            now --token $ZEIT_TOKEN --team spaceprogram
            sleep 1 # This might fix the problem where now aliases the old deploy from hyperion
            now --token $ZEIT_TOKEN --team spaceprogram alias api.alpha.spectrum.chat
            cd ..
      - run:
          name: Deploy and alias Hyperion
          command: |
            now --token $ZEIT_TOKEN --team spaceprogram
            now --token $ZEIT_TOKEN --team spaceprogram alias hyperion.alpha.spectrum.chat


  # Run eslint, flow etc.
  test_static_js:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: ~/spectrum
      - run:
          name: Run Flow
          command: yarn run flow
      - run:
          name: Run ESLint
          command: yarn run lint

  # Tests js of the mobile app
  test_mobile_js:
    <<: *js_defaults
    steps:
      - attach_workspace:
          at: ~/spectrum
      - run: cd ./mobile && yarn test:unit

  # Tests native code of the mobile app
  test_mobile_native:
    <<: *macos_defaults
    steps:
      - attach_workspace:
          at: ~/spectrum
      - run:
          name: Install Expo CLI
          command: npm install -g exp
      - run:
          name: Install Detox dependencies
          command: |
            brew tap wix/brew
            brew install applesimutils --HEAD
            npm install -g detox-cli
      - run:
          name: Rebuild Detox frameworks
          command: |
            cd ./mobile
            detox clean-framework-cache
            detox build-framework-cache
      - run:
          name: Start Packager in the background
          command: cd ./mobile && exp start
          background: true
      - run: cd ./mobile && yarn test:e2e

workflows:
  version: 2

  test:
    jobs:
      - checkout_environment
      - test_mobile_js:
          requires:
            - checkout_environment

      # Disabled as Expo is fixing their critical issue with Detox
      # - test_mobile_native:
      #     requires:
      #       - checkout_environment
      - test_web:
          requires:
            - checkout_environment
      - test_static_js:
          requires:
            - checkout_environment
      - deploy_alpha:
          requires:
            - test_static_js
            - test_web
          filters:
            branches:
              only: alpha
